# Generated by Django 2.1.3 on 2019-03-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='世界名校', max_length=10, verbose_name='机构标签'),
        ),
    ]
