# Generated by Django 2.1.3 on 2019-03-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='课文', max_length=20, verbose_name='课程类别'),
        ),
    ]
